
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-west-2

managedNodeGroups:
- name: ManagedNG-1
  desiredCapacity: 1
  instanceType: t3.small
  ssh:
    enableSsm: true
